### ISSUE TITLE
Cannot load modules that add a command

### ISSUE THREAD

**Issue by HakuryuuDom** [Mathicha/manager#1]
https://i.imgur.com/pkWqtv3.png unloading works fine, but i cant load it again. mod link: https://github.com/SerenTera/npc-replacer

**Comment by Mathicha** [comment]
The problem is that in npc-replacer there is no destructor that [removes](
https://github.com/pinkipi/command/blob/master/index.js#L148-L158) the added command when the module is unloaded

Ask the creator of the module to add something like 
`this.destructor = () => { command.remove('cn') };`

Or add the destructor yourself 😉
